# 🐍 Fundamentos de Manipulação de Dados com NumPy e Pandas

## 🎯 Objetivos da Aula

Ao final desta aula, você será capaz de:
- ✅ Entender as principais estruturas de dados do NumPy e Pandas
- ✅ Realizar operações matemáticas e estatísticas eficientes
- ✅ Manipular, filtrar e transformar dados
- ✅ Aplicar técnicas de análise exploratória de dados
- ✅ Visualizar dados de forma básica

---

## 📚 Pré-requisitos
- Conhecimento básico de Python
- Familiaridade com estruturas de dados (listas, dicionários)
- Conceitos básicos de estatística

---

## 🔍 Introdução às Bibliotecas

### 🧮 NumPy (Numerical Python)
> **Propósito:** Computação numérica eficiente e operações matemáticas avançadas

**Principais características:**
- 🚀 **Performance:** Até 100x mais rápido que listas Python nativas
- 🎯 **Estrutura principal:** `ndarray` (N-dimensional array)
- 🧮 **Funcionalidades:** Álgebra linear, transformadas de Fourier, números aleatórios
- 🔧 **Base:** Fundação para outras bibliotecas científicas (Pandas, Scikit-learn, etc.)

### 📊 Pandas (Panel Data)
> **Propósito:** Manipulação e análise de dados estruturados (tabulares)

**Principais características:**
- 📋 **Estruturas:** Series (1D) e DataFrame (2D)
- 🛠️ **Funcionalidades:** Limpeza, transformação, agregação e análise de dados
- 📁 **I/O:** Leitura/escrita de diversos formatos (CSV, Excel, JSON, SQL, etc.)
- 🎨 **Integração:** Funciona perfeitamente com NumPy e bibliotecas de visualização

---

> **💡 Dica:** NumPy é ideal para cálculos matemáticos, enquanto Pandas é perfeito para análise de dados do mundo real!

# 🧮 NumPy: Computação Numérica Eficiente

## 🎯 O que veremos nesta seção:
1. 🏗️ Criação de arrays
2. 🔢 Operações matemáticas e broadcasting
3. 🎯 Indexação e slicing avançado
4. 📐 Manipulação de formas e dimensões
5. 📊 Funções estatísticas e agregações
6. 🎲 Geração de números aleatórios

---

**O que é NumPy e por que usá-lo?**

- NumPy (Numerical Python) é a biblioteca base para computação científica em Python.   

- Sua principal estrutura é o ndarray (array multidimensional), que é muito mais rápido e eficiente para operações matemáticas do que as listas nativas do Python.

## 🏗️ Criando Arrays

### 📋 Principais métodos de criação:
- **`np.array()`** - A partir de listas/tuplas
- **`np.arange()`** - Sequências numéricas
- **`np.linspace()`** - Valores igualmente espaçados
- **`np.zeros()`** - Arrays preenchidos com zeros
- **`np.ones()`** - Arrays preenchidos com uns
- **`np.random.random()`** - Arrays com valores aleatórios

In [1]:
# Importando a biblioteca NumPy
import numpy as np
print(f"NumPy versão: {np.__version__}")

NumPy versão: 2.1.2

In [2]:
# A partir de uma lista Python
lista = [1, 2, 3, 4, 5]
array_de_lista = np.array(lista)
print(f"Array a partir de lista: {array_de_lista}")

Array a partir de lista: [1 2 3 4 5]

In [3]:
# Criando um array com uma sequência de valores (de 0 a 8, pulando de 2 em 2)
array_arange = np.arange(0, 10, 2)
print(f"Array com arange: {array_arange}")

Array com arange: [0 2 4 6 8]

In [4]:
# Criando um array de 5 números igualmente espaçados entre 0 e 1
array_linspace = np.linspace(0, 1, 5)
print(f"Array com linspace: {array_linspace}")

Array com linspace: [0.   0.25 0.5  0.75 1.  ]

In [5]:
# Criando uma matriz (array 2D) de zeros
matriz_zeros = np.zeros((2, 3))
print("Matriz de zeros:\n", matriz_zeros)

Matriz de zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

In [6]:
# Criando uma matriz (array 2D) de uns
matriz_uns = np.ones((3, 4))
print("Matriz de uns:")
print(matriz_uns)

Matriz de uns:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [7]:
# Criando uma matriz identidade
matriz_identidade = np.eye(3)
print("\nMatriz identidade:")
print(matriz_identidade)

Matriz identidade:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [8]:
# Criando um array com valores aleatórios
array_aleatorio = np.random.random((2, 3))
print("\nArray aleatório:")
print(array_aleatorio)

Array aleatório:
[[0.73389585 0.8118012  0.91226253]
 [0.21810613 0.2649065  0.83626822]]

### 🔍 Propriedades dos Arrays

In [9]:
# Explorando propriedades dos arrays
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print("Array original:")
print(matriz)
print(f"Forma (shape): {matriz.shape}")
print(f"Dimensões (ndim): {matriz.ndim}")
print(f"Tamanho total (size): {matriz.size}")
print(f"Tipo de dados (dtype): {matriz.dtype}")
print(f"Bytes por elemento: {matriz.itemsize}")
print(f"Memória total: {matriz.nbytes} bytes")

Array original:
[[1 2 3]
 [4 5 6]]
Forma (shape): (2, 3)
Dimensões (ndim): 2
Tamanho total (size): 6
Tipo de dados (dtype): int64
Bytes por elemento: 8
Memória total: 48 bytes

## Operações com Arrays

In [10]:
# Mais operações matemáticas
x = np.array([1, 4, 9, 16, 25])
y = np.array([2, 3, 4, 5, 6])

print("Array x:", x)
print("Array y:", y)
print()

# Raiz quadrada
print("Raiz quadrada de x:", np.sqrt(x))

# Potência
print("y elevado ao quadrado:", np.power(y, 2))

# Funções trigonométricas
angulos = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Seno dos ângulos:", np.sin(angulos))

# Exponencial e logaritmo
print("Exponencial de [1, 2, 3]:", np.exp([1, 2, 3]))
print("Logaritmo natural de [1, 2, 3]:", np.log([1, 2, 3]))

Array x: [ 1  4  9 16 25]
Array y: [2 3 4 5 6]

Raiz quadrada de x: [1. 2. 3. 4. 5.]
y elevado ao quadrado: [ 4  9 16 25 36]
Seno dos ângulos: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Exponencial de [1, 2, 3]: [ 2.71828183  7.3890561  20.08553692]
Logaritmo natural de [1, 2, 3]: [0.         0.69314718 1.09861229]

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

soma = a + b
print(f"Soma: {soma}") 

multiplicacao = a * 2
print(f"Multiplicação por escalar: {multiplicacao}") 

# Broadcasting: operando com arrays de tamanhos diferentes
matriz = np.array([[1, 2, 3], [4, 5, 6]])
escalar = 10

soma_broadcast = matriz + escalar
print("Soma com broadcasting:\n", soma_broadcast)

Soma: [5 7 9]
Multiplicação por escalar: [2 4 6]
Soma com broadcasting:
 [[11 12 13]
 [14 15 16]]

### 📊 Funções estatísticas e agregações

In [12]:
# Criando dados para análise estatística
np.random.seed(42)  # Para reproduzibilidade
dados_vendas = np.random.normal(1000, 200, 100)  # 100 vendas com média 1000 e desvio 200

print("Dados de vendas (primeiros 10 valores):")
print(dados_vendas[:10])
print()

# Estatísticas descritivas
print("=== ESTATÍSTICAS DESCRITIVAS ===")
print(f"Média: {np.mean(dados_vendas):.2f}")
print(f"Mediana: {np.median(dados_vendas):.2f}")
print(f"Desvio padrão: {np.std(dados_vendas):.2f}")
print(f"Variância: {np.var(dados_vendas):.2f}")
print(f"Mínimo: {np.min(dados_vendas):.2f}")
print(f"Máximo: {np.max(dados_vendas):.2f}")
print()

# Percentis
print("=== PERCENTIS ===")
print(f"25º percentil: {np.percentile(dados_vendas, 25):.2f}")
print(f"50º percentil (mediana): {np.percentile(dados_vendas, 50):.2f}")
print(f"75º percentil: {np.percentile(dados_vendas, 75):.2f}")
print()

# Soma e produto
print("=== AGREGAÇÕES ===")
print(f"Soma total: {np.sum(dados_vendas):.2f}")
print(f"Produto dos 5 primeiros: {np.prod(dados_vendas[:5]):.2e}")
print(f"Soma acumulada (primeiros 5): {np.cumsum(dados_vendas[:5])}")

Dados de vendas (primeiros 10 valores):
[1099.3428306   972.34713977 1129.53770762 1304.60597128  953.16932506
  953.17260861 1315.8425631  1153.48694583  906.10512281 1108.51200872]

=== ESTATÍSTICAS DESCRITIVAS ===
Média: 979.23
Mediana: 974.61
Desvio padrão: 180.72
Variância: 32660.89
Mínimo: 476.05
Máximo: 1370.46

=== PERCENTIS ===
25º percentil: 879.82
50º percentil (mediana): 974.61
75º percentil: 1081.19

=== AGREGAÇÕES ===
Soma total: 97923.07
Produto dos 5 primeiros: 1.50e+15
Soma acumulada (primeiros 5): [1099.3428306  2071.68997037 3201.22767799 4505.83364927 5459.00297433]

### 📐 Manipulação de Formas e Dimensões

In [13]:
# Criando um array para manipulação
arr = np.arange(12)
print("Array original:")
print(f"Valores: {arr}")
print(f"Forma: {arr.shape}")
print()

# Reshape - mudando a forma
arr_2d = arr.reshape(3, 4)
print("Array 2D (3x4):")
print(arr_2d)
print(f"Forma: {arr_2d.shape}")
print()

# Reshape para 3D
arr_3d = arr.reshape(2, 2, 3)
print("Array 3D (2x2x3):")
print(arr_3d)
print(f"Forma: {arr_3d.shape}")
print()

# Flatten - achatar o array
arr_flat = arr_3d.flatten()
print("Array achatado:")
print(f"Valores: {arr_flat}")
print(f"Forma: {arr_flat.shape}")
print()

Array original:
Valores: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Forma: (12,)

Array 2D (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Forma: (3, 4)

Array 3D (2x2x3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Forma: (2, 2, 3)

Array achatado:
Valores: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Forma: (12,)

In [14]:
# Transpose - transpor matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz original:")
print(matriz)
print(f"Forma: {matriz.shape}")
print()

matriz_t = matriz.T
print("Matriz transposta:")
print(matriz_t)
print(f"Forma: {matriz_t.shape}")
print()

# Concatenação
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat_h = np.concatenate([arr1, arr2])
print(f"Concatenação horizontal: {concat_h}")

# Stack vertical
stack_v = np.vstack([arr1, arr2])
print("Stack vertical:")
print(stack_v)

Matriz original:
[[1 2 3]
 [4 5 6]]
Forma: (2, 3)

Matriz transposta:
[[1 4]
 [2 5]
 [3 6]]
Forma: (3, 2)

Concatenação horizontal: [1 2 3 4 5 6]
Stack vertical:
[[1 2 3]
 [4 5 6]]

## Indexação e Slicing

In [15]:
# Array para os exemplos
dados = np.arange(10, 20)
print(f"Array original: {dados}")

Array original: [10 11 12 13 14 15 16 17 18 19]

In [16]:
# Acessando um elemento (o terceiro elemento, índice 2)
print(f"Elemento no índice 2: {dados[2]}")

Elemento no índice 2: 12

In [17]:
# Slicing: pegando um subconjunto (do índice 2 ao 5)
print(f"Slicing de 2 a 5: {dados[2:6]}")

Slicing de 2 a 5: [12 13 14 15]

In [18]:
# Indexação booleana: pegando apenas os números maiores que 15
maiores_que_15 = dados[dados > 15]
print(f"Números maiores que 15: {maiores_que_15}")

# Indexação booleana com operações lógicas
maiores_que_15_ou_menores_que_12 = dados[(dados > 15) | (dados < 12)]
print(f"Números maiores que 15 ou menores que 12: {maiores_que_15_ou_menores_que_12}")

Números maiores que 15: [16 17 18 19]
Números maiores que 15 ou menores que 12: [10 11 16 17 18 19]

In [19]:
# Usando np.where para substituir valores
# Substitui números pares por -1
dados_modificados = np.where(dados % 2 == 0, -1, dados)
print(f"Pares substituídos por -1: {dados_modificados}")

Pares substituídos por -1: [-1 11 -1 13 -1 15 -1 17 -1 19]

# 📊 Pandas: Análise e Manipulação de Dados

**O que é Pandas? Series e DataFrames**

- Pandas é construído sobre o NumPy e facilita a manipulação de dados tabulares.   

- As duas estruturas principais são:   

    - Series: Um array unidimensional com rótulos (índices). Pense nela como uma única coluna de uma tabela.   

    - DataFrame: Uma estrutura bidimensional, como uma tabela ou planilha, onde cada coluna é uma Series.

## Criando Series e DataFrames

In [20]:
# Importando a biblioteca Pandas
import pandas as pd
print(f"Pandas versão: {pd.__version__}")

# Criando uma Series a partir de uma lista
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series:")
print(s)

Pandas versão: 2.2.3
Series:
a    10
b    20
c    30
d    40
dtype: int64

## 🔄 Transformação e Limpeza de Dados

Uma das principais aplicações do Pandas é a limpeza e transformação de dados para análise.

In [21]:
# Criando um DataFrame com dados "sujos" para demonstrar limpeza
import numpy as np

dados_sujos = {
    'Nome': ['josé','João', 'Ana', 'PEDRO', 'maria', 'Carlos', ''],
    'Idade': [80, 28, 24, 35, None, 45, 30],
    'Salario': [7000, 5000, 6000, None, 4500, 7000, 5500],
    'Cidade': ['Brasília', 'São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'Curitiba', 'Fortaleza']
}

df_sujo = pd.DataFrame(dados_sujos)
print("DataFrame com dados 'sujos':")
df_sujo

DataFrame com dados 'sujos':

     Nome  Idade  Salario          Cidade
0    josé   80.0   7000.0        Brasília
1    João   28.0   5000.0       São Paulo
2     Ana   24.0   6000.0  Rio de Janeiro
3   PEDRO   35.0      NaN  Belo Horizonte
4   maria    NaN   4500.0        Salvador
5  Carlos   45.0   7000.0        Curitiba
6           30.0   5500.0       Fortaleza

In [22]:
# Verificando dados faltantes
print("Dados faltantes por coluna:")
print(df_sujo.isnull().sum())
print()

Dados faltantes por coluna:
Nome       0
Idade      1
Salario    1
Cidade     0
dtype: int64

In [23]:
# Limpando os dados
df_limpo = df_sujo.copy()

# 1. Removendo linhas com nome vazio
df_limpo = df_limpo[df_limpo['Nome'] != '']

# 2. Padronizando nomes (primeira letra maiúscula)
df_limpo['Nome'] = df_limpo['Nome'].str.title()

# 3. Preenchendo valores faltantes
df_limpo['Idade'] = df_limpo['Idade'].fillna(df_limpo['Idade'].median())
df_limpo['Salario'] = df_limpo['Salario'].fillna(df_limpo['Salario'].mean())
print("DataFrame após limpeza:")
df_limpo

DataFrame após limpeza:

     Nome  Idade  Salario          Cidade
0    José   80.0   7000.0        Brasília
1    João   28.0   5000.0       São Paulo
2     Ana   24.0   6000.0  Rio de Janeiro
3   Pedro   35.0   5900.0  Belo Horizonte
4   Maria   35.0   4500.0        Salvador
5  Carlos   45.0   7000.0        Curitiba

In [24]:
# Criando nova coluna baseada em outra
df_limpo['Faixa_Etaria'] = df_limpo['Idade'].apply(lambda x: 'Jovem' if x < 30 else 'Adulto' if x < 50 else 'Maduro')
df_limpo['Salario_Categoria'] = pd.cut(df_limpo['Salario'], bins=[0, 5000, 6000, 10000], labels=['Baixo', 'Médio', 'Alto'])

print("DataFrame com novas colunas:")
df_limpo

DataFrame com novas colunas:

     Nome  Idade  Salario          Cidade Faixa_Etaria Salario_Categoria
0    José   80.0   7000.0        Brasília       Maduro              Alto
1    João   28.0   5000.0       São Paulo        Jovem             Baixo
2     Ana   24.0   6000.0  Rio de Janeiro        Jovem             Médio
3   Pedro   35.0   5900.0  Belo Horizonte       Adulto             Médio
4   Maria   35.0   4500.0        Salvador       Adulto             Baixo
5  Carlos   45.0   7000.0        Curitiba       Adulto              Alto

## 📈 Operações de Agrupamento e Agregação

O `groupby` é uma das funcionalidades mais poderosas do Pandas para análise de dados.

In [25]:
# Criando um DataFrame mais robusto para demonstrar groupby
np.random.seed(42)

dados_vendas = {
    'Vendedor': ['Ana', 'João', 'Pedro', 'Ana', 'João', 'Pedro', 'Ana', 'João', 'Pedro', 'Ana'] * 3,
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset'] * 6,
    'Regiao': ['Norte', 'Sul', 'Nordeste', 'Centro-Oeste', 'Sudeste'] * 6,
    'Vendas': np.random.randint(1000, 10000, 30),
    'Quantidade': np.random.randint(1, 20, 30)
}

df_vendas_completo = pd.DataFrame(dados_vendas)
print("DataFrame de vendas:")
df_vendas_completo.head(10)

DataFrame de vendas:

  Vendedor   Produto        Regiao  Vendas  Quantidade
0      Ana  Notebook         Norte    8270          12
1     João     Mouse           Sul    1860           3
2    Pedro   Teclado      Nordeste    6390           5
3      Ana   Monitor  Centro-Oeste    6191          19
4     João   Headset       Sudeste    6734           7
5    Pedro  Notebook         Norte    7265           9
6      Ana     Mouse           Sul    1466           7
7     João   Teclado      Nordeste    5426          18
8    Pedro   Monitor  Centro-Oeste    6578           4
9      Ana   Headset       Sudeste    9322          14

In [26]:

# Agrupamento simples - vendas por vendedor
vendas_por_vendedor = df_vendas_completo.groupby('Vendedor')['Vendas'].sum()
print("Vendas totais por vendedor:")
vendas_por_vendedor

Vendas totais por vendedor:

Vendedor
Ana      66264
João     40731
Pedro    51098
Name: Vendas, dtype: int32

In [27]:

# Múltiplas agregações
agregacoes = df_vendas_completo.groupby('Vendedor')['Vendas'].agg(['sum', 'mean', 'count'])
print("Múltiplas agregações por vendedor:")
agregacoes

Múltiplas agregações por vendedor:

            sum         mean  count
Vendedor
Ana       66264  5522.000000     12
João      40731  4525.666667      9
Pedro     51098  5677.555556      9

In [28]:

# Agrupamento por múltiplas colunas
vendas_por_vendedor_regiao = df_vendas_completo.groupby(['Vendedor', 'Regiao'])['Vendas'].sum()
print("Vendas por vendedor e região:")
vendas_por_vendedor_regiao

Vendas por vendedor e região:

Vendedor  Regiao
Ana       Centro-Oeste    18473
          Norte           18351
          Sudeste         19365
          Sul             10075
João      Nordeste        11344
          Sudeste         16092
          Sul             13295
Pedro     Centro-Oeste    16138
          Nordeste        17897
          Norte           17063
Name: Vendas, dtype: int32

In [29]:

# Pivot table
pivot_vendas = df_vendas_completo.pivot_table(
    values='Vendas', 
    index='Vendedor', 
    columns='Produto', 
    aggfunc='sum', 
    fill_value=0
)
print("Pivot table - Vendas por Vendedor x Produto:")
pivot_vendas

Pivot table - Vendas por Vendedor x Produto:

Produto   Headset  Monitor  Mouse  Notebook  Teclado
Vendedor
Ana         19365    18473  10075     18351        0
João        16092        0  13295         0    11344
Pedro           0    16138      0     17063    17897

In [30]:
# Estatísticas descritivas por grupo
print("Estatísticas descritivas por região:")
df_vendas_completo.groupby('Regiao')['Vendas'].describe()

Estatísticas descritivas por região:

,count,mean,std,min,25%,50%,75%,max
Regiao,,,,,,,,
Centro-Oeste,6.0,5768.500000,1945.936869,3433.0,4392.50,5873.0,6481.25,8849.0
Nordeste,6.0,4873.500000,2113.108587,2184.0,3602.00,4580.0,6149.00,7949.0
Norte,6.0,5902.333333,2223.175357,2685.0,4323.00,6658.0,7363.25,8270.0
Sudeste,6.0,5909.500000,2147.902116,3047.0,4703.25,5984.5,6628.25,9322.0
Sul,6.0,3895.000000,3677.326311,1189.0,1541.75,1814.5,6030.00,9666.0

## 💾 Leitura e Escrita de Arquivos

O Pandas oferece suporte a diversos formatos de arquivo, facilitando a importação e exportação de dados.

In [31]:
# Salvando o DataFrame em CSV
df_vendas_completo.to_csv('vendas_exemplo.csv', index=False)
print("✅ Arquivo 'vendas_exemplo.csv' salvo com sucesso!")

# Lendo o arquivo CSV
df_lido = pd.read_csv('vendas_exemplo.csv')
print("\n📂 Dados lidos do arquivo CSV:")
df_lido.head()

✅ Arquivo 'vendas_exemplo.csv' salvo com sucesso!

📂 Dados lidos do arquivo CSV:

  Vendedor   Produto        Regiao  Vendas  Quantidade
0      Ana  Notebook         Norte    8270          12
1     João     Mouse           Sul    1860           3
2    Pedro   Teclado      Nordeste    6390           5
3      Ana   Monitor  Centro-Oeste    6191          19
4     João   Headset       Sudeste    6734           7

## 🎯 Exercícios Práticos

### 💪 Desafio 1: Análise de Dados de Vendas
Usando os dados que criamos, responda às seguintes perguntas:

1. **Qual vendedor teve o maior número de vendas?**
2. **Qual região teve o maior faturamento total?**
3. **Qual é o produto mais vendido em quantidade?**
4. **Qual é a média de vendas por vendedor?**

### 🔧 Desafio 2: Limpeza de Dados
Crie um DataFrame com dados "problemáticos" e implemente:
- Remoção de duplicatas
- Tratamento de valores ausentes
- Padronização de strings
- Criação de novas colunas derivadas

### 📊 Desafio 3: Visualização
Crie gráficos que mostrem:
- Comparação entre vendedores
- Tendências por região
- Distribuição dos valores

**💡 Dica:** Use os exemplos anteriores como base e experimente modificar os parâmetros!

## 🎓 Conclusão e Próximos Passos

### 🏆 O que você aprendeu hoje:

#### 🧮 NumPy
- ✅ Criação e manipulação de arrays multidimensionais
- ✅ Operações matemáticas eficientes
- ✅ Indexação, slicing e filtragem
- ✅ Funções estatísticas e agregações
- ✅ Manipulação de formas e dimensões

#### 📊 Pandas
- ✅ Criação de Series e DataFrames
- ✅ Exploração e análise de dados
- ✅ Limpeza e transformação de dados
- ✅ Agrupamento e agregação
- ✅ Visualização básica
- ✅ Leitura e escrita de arquivos

---

### 🚀 Próximos Passos Recomendados:

1. **📈 Visualização Avançada**
   - Seaborn para gráficos estatísticos
   - Plotly para visualizações interativas
   - Matplotlib avançado

2. **🤖 Machine Learning**
   - Scikit-learn para algoritmos de ML
   - Preparação de dados para modelos
   - Análise preditiva

3. **🗃️ Bancos de Dados**
   - SQLAlchemy para conexão com bancos
   - Análise de grandes volumes de dados
   - Otimização de consultas

4. **⚡ Performance**
   - Dask para processamento paralelo
   - Numba para aceleração de código
   - Técnicas de otimização

5. **🌐 Web Scraping e APIs**
   - Requests e BeautifulSoup
   - Coleta de dados em tempo real
   - Automatização de processos

---

### 📚 Recursos Adicionais:

- **Documentação oficial:** [NumPy](https://numpy.org/doc/) | [Pandas](https://pandas.pydata.org/docs/)
- **Tutoriais:** [Pandas Tutorial](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)
- **Livros:** "Python for Data Analysis" por Wes McKinney
- **Cursos:** DataCamp, Coursera, edX

---

### 🎯 Lembre-se:
> *"A prática leva à perfeição. Continue experimentando com diferentes datasets e explore as funcionalidades avançadas!"*

**Obrigado pela atenção! 🙏**

## 📋 Cheat Sheet - Comandos Essenciais

### 🧮 NumPy
```python
import numpy as np

# Criação de arrays
np.array([1, 2, 3])          # De lista
np.arange(0, 10, 2)          # Sequência
np.linspace(0, 1, 5)         # Espaçamento linear
np.zeros((3, 4))             # Matriz de zeros
np.ones((2, 3))              # Matriz de uns
np.random.random((2, 3))     # Valores aleatórios

# Operações
arr.shape                    # Forma do array
arr.dtype                    # Tipo de dados
arr.reshape(3, 4)            # Mudar forma
arr.T                        # Transpor
arr.sum()                    # Soma
arr.mean()                   # Média
arr.std()                    # Desvio padrão
```

### 📊 Pandas
```python
import pandas as pd

# Criação
pd.Series([1, 2, 3])         # Series
pd.DataFrame(dict)           # DataFrame de dicionário

# Leitura/Escrita
pd.read_csv('file.csv')      # Ler CSV
df.to_csv('file.csv')        # Salvar CSV

# Exploração
df.head()                    # Primeiras linhas
df.info()                    # Informações
df.describe()                # Estatísticas
df.isnull().sum()           # Valores ausentes

# Seleção
df['coluna']                 # Uma coluna
df[['col1', 'col2']]        # Múltiplas colunas
df[df['col'] > 5]           # Filtrar

# Agrupamento
df.groupby('col').sum()      # Agrupar e somar
df.pivot_table(...)          # Tabela dinâmica
```

**💡 Mantenha este cheat sheet sempre à mão!**